---
title: "MLB Data"
author: "CS"
date: "9/15/2021"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  fig.retina = 3,
  fig.path = here::here("exports", "MLB", "Plots", "/")
)
pacman::p_load(pacman, tidyverse, janitor, here, rio, job, skimr)
theme_set(theme_bw(base_size = 15))
```

```{r mlb-data, include = F}
p_load(Lahman, pitchRx, retrosheet, openWAR, baseballr, teamcolors, zoo)

#browseURL("https://tht.fangraphs.com/author/billpetti/")

#browseURL("https://billpetti.github.io/baseballr/")

# betts_id <- playerid_lookup("Betts") %>%
#   filter(first_name == "Mookie") %>%
#   select(mlbam_id, first_name, last_name)

oneill_id <- playerid_lookup("Neill") %>% 
  filter(first_name == "Tyler") %>% 
  select(mlbam_id, first_name, last_name)

goldy_id <- playerid_lookup("Goldsch") %>% 
  filter(first_name == "Paul") %>% 
  select(mlbam_id, first_name, last_name)

hit_sum <- function(df){
  df  %>% 
    select(game_date, events, home_team, away_team) %>% 
    filter(!is.na(events)) %>% 
    group_by(game_date) %>%
    mutate(hits = sum(events %in% c("single", "double", "triple", "home_run")),
           pa = sum(!is.na(events == T)),
           ab = pa - sum(events %in% c("hit_by_pitch", "sac_fly", "walk")),
           game_avg = hits/ab) %>% 
    ungroup() %>% 
    arrange(game_date) %>% 
    group_by(isna = is.na(game_avg)) %>% 
    mutate(avg = ifelse(isna, NA, round(cummean(game_avg), 3))) %>% 
#    group_by(game_date) %>% 
    mutate(avg_25_ab = rollmean(avg, k = 25, fill = NA))
}

# sum_oneill <- hit_sum(oneill_2021)

mlb_colors <- teamcolors %>% 
  select(name, league, primary, secondary, tertiary, quaternary) %>% 
  filter(league == "mlb") %>% 
  mutate(team_abbr = case_when(name == "Arizona Diamondbacks" ~ "AZ",
                                 name == "Atlanta Braves" ~ "ATL",
                                 name == "Baltimore Orioles" ~ "BAL",
                                 name == "Boston Red Sox" ~ "BOS",
                                 name == "Chicago Cubs" ~ "CHC",
                                 name == "Chicago White Sox" ~ "CWS",
                                 name == "Cincinnati Reds" ~ "CIN",
                                 name == "Cleveland Indians" ~ "CLE",
                                 name == "Colorado Rockies" ~ "COL",
                                 name == "Detroit Tigers" ~ "DET",
                                 name == "Houston Astros" ~ "HOU",
                                 name == "Kansas City Royals" ~ "KC",
                                 name == "Los Angeles Angels" ~ "LAA",
                                 name == "Los Angeles Dodgers" ~ "LAD",
                                 name == "Miami Marlins" ~ "MIA",
                                 name == "Milwaukee Brewers" ~ "MIL",
                                 name == "Minnesota Twins" ~ "MIN",
                                 name == "New York Mets" ~ "NYM",
                                 name == "New York Yankees" ~ "NYY",
                                 name == "Oakland Athletics" ~ "OAK",
                                 name == "Philadelphia Phillies" ~ "PHI",
                                 name == "Pittsburgh Pirates" ~ "PIT",
                                 name == "San Diego Padres" ~ "SD",
                                 name == "San Francisco Giants" ~ "SF",
                                 name == "Seattle Mariners" ~ "SEA",
                                 name == "St. Louis Cardinals" ~ "STL",
                                 name == "Tampa Bay Rays" ~ "TB",
                                 name == "Texas Rangers" ~ "TEX",
                                 name == "Toronto Blue Jays" ~ "TOR",
                                 name == "Washington Nationals" ~ "WSH")
         )



```

## Tyler O'Neill

```{r, include = F}
oneill_2021 <- scrape_statcast_savant(start_date = "2021-03-31", end_date = Sys.Date()-1,
                                      playerid = oneill_id[1, 1], player_type = "batter")

skim(oneill_2021)
```

```{r}
oneill_2021 %>% 
  group_by(game_date) %>% 
  select(launch_speed) %>% 
  summarize_all(mean, na.rm = T) %>% 
  ggplot(aes(game_date, launch_speed)) + 
  geom_point() + 
  geom_smooth(method = "lm", se = F)
```

```{r}
sum_oneill <- hit_sum(oneill_2021)
```

```{r}
sum_oneill %>% 
  ggplot(aes(game_date, avg)) + 
  geom_point() + 
#  geom_smooth(method = "loess", se = F) +
  geom_line(aes(x = game_date, y = avg_25_ab), color = "blue") +
  lims(y = c(.100, .400))
```

# Paul Goldschmidt

```{r}
goldy_2021 <- scrape_statcast_savant(start_date = "2021-03-31", end_date = Sys.Date()-1,
                                      playerid = goldy_id[1, 1], player_type = "batter")

goldy_sum <- hit_sum(goldy_2021)

goldy_sum %>% 
  ggplot(aes(game_date, avg)) + 
  geom_jitter(color = "#c41e3a") + 
#  geom_smooth(method = "loess", se = F) +
  geom_line(aes(x = game_date, y = avg_25_ab), color = "#fedb00") +
  lims(y = c(.100, .400))
```

