---
title: "Soccer Data"
author: "CS"
date: "9/15/2021"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  fig.retina = 3,
  fig.path = here::here("exports", "soccer", "Plots", "/")
)
pacman::p_load(pacman, tidyverse, janitor, here, rio, job, skimr, patchwork, viridis)
theme_set(theme_bw(base_size = 15))
```

```{r, include = F}

# browseURL("https://ryo-n7.github.io/2019-08-21-visualize-soccer-statsbomb-part-1/")
# browseURL("https://github.com/JoGall/soccermatics")

p_load(StatsBombR, SBpitch, soccermatics)

comps <- FreeCompetitions()

laliga_2020 <- comps %>% 
  filter(competition_id == 11, season_id == 42) %>% 
  FreeMatches()

barca_raw <-  StatsBombFreeEvents(MatchesDF = laliga_2020)

round_angle <- 30

barca_sum <- barca_raw %>%
  mutate(angle.round = round(pass.angle*180/pi/round_angle)*round_angle, .before = id,
         pass_angle = pass.angle,
         pass_length = case_when(pass.length >= 30 ~ 30,
                                 TRUE ~ pass.length))

barca_sonar <- barca_sum %>% 
  filter(team.name == "Barcelona") %>% 
  filter(type.name == "Pass", # passes only
         !play_pattern.name %in% c("From Corner", "From Free Kick", "From Throw In")) %>% # remove deadballs
  group_by(player.name, team.name) %>% # group by player and team
  mutate(total_passes = n(), .before = id) %>% # add total passes and put before id
  ungroup() %>% 
  group_by(player.name, team.name, angle.round) %>% # group by these
  mutate(passes_per_angle = n(),
         pct.angle = (n()/total_passes)*100, .before = total_passes) %>% # add number per angle bracket and percent per angle bracket
  ungroup() %>%
  group_by(player.name, team.name) %>% # group by these
  mutate(maxN = max(passes_per_angle), # pull out maximum n of passes per angle per player
         angle.norm = passes_per_angle/maxN, .before = total_passes) %>% # calc final number per max number
  ungroup() %>%
  group_by(angle.round, player.name, team.name,total_passes) %>%
  summarize(angle.norm = mean(angle.norm), # calc mean angle
            pct.angle = mean(pct.angle), # calc mean pct per angle
            distance = mean(pass.length), # calc mean pass length
            distance = ifelse(distance>30, 30,distance)) # cap distance at 30m
```

```{r, barca-plot-attempt-1}
barca_raw %>% 
  filter(!is.na(pass.angle)) %>% 
  filter(possession_team.name == "Barcelona") %>% 
  ggplot(aes(pass.angle)) + 
  geom_density() + 
  lims(x = c(-pi, pi)) +
  coord_polar(start = pi)
```


```{r, include = F, eval = F}
# browseURL("https://github.com/etmckinley/PassSonar/blob/master/StatsBomb%20PassSonars.R")

barca_sum %>% 
  filter(!is.na(pass.angle)) %>% 
  filter(possession_team.name == "Barcelona") %>% 
  ggplot(aes(angle.round, fill = pass.length)) + 
  geom_histogram(bins = 50, color = "black")

```

```{r, messi-sonar-1}
(messi <- barca_sonar %>% 
  filter(str_detect(player.name, "Messi")) %>% 
  ggplot() +
  geom_bar(aes(x=angle.round, y=pct.angle, fill=distance), stat="identity")+
  scale_y_continuous(limits=c(0,25))+
  scale_x_continuous(breaks=seq(-180,180, by=90), limits=c(-180,180))+
  coord_polar(start=pi, direction=1)+
  scale_fill_viridis("Distance (yards)", limits=c(0,30), na.value="#FDE725FF")+
  labs(x='', y='',title= "Messi")+
  theme_void()+
  theme(plot.title = element_text(hjust=0.5),
        #legend.position = "none", #uncomment to remove colorbar
        plot.background = element_rect(fill = "transparent",colour = NA),
        panel.background = element_rect(fill = "transparent",colour = NA))
)
```

```{r, wague-test-1}
(wague <- barca_sonar %>% 
  filter(str_detect(player.name, "Wagu")) %>% 
  ggplot() +
  geom_bar(aes(x=angle.round, y=pct.angle, fill=distance), stat="identity")+
  scale_y_continuous(limits=c(0,25))+
  scale_x_continuous(breaks=seq(-180,180, by=90), limits=c(-180,180))+
  coord_polar(start=pi, direction=1)+
  scale_fill_viridis("Distance (yards)", limits=c(0,30), na.value="#FDE725FF")+
  labs(x='', y='',title= "Wague")+
  theme_void()+
  theme(plot.title = element_text(hjust=0.5),
        #legend.position = "none", #uncomment to remove colorbar
        plot.background = element_rect(fill = "transparent",colour = NA),
        panel.background = element_rect(fill = "transparent",colour = NA))
)
```

```{r, busquets-test-1}
(busquets <- barca_sonar %>% 
  filter(str_detect(player.name, "Busquets")) %>% 
  ggplot() +
  geom_bar(aes(x=angle.round, y=pct.angle, fill=distance), stat="identity")+
  scale_y_continuous(limits=c(0,25))+
  scale_x_continuous(breaks=seq(-180,180, by=90), limits=c(-180,180))+
  coord_polar(start=pi, direction=1)+
  scale_fill_viridis("Distance (yards)", limits=c(0,30), na.value="#FDE725FF")+
  labs(x='', y='',title= "Busquets")+
  theme_void()+
  theme(plot.title = element_text(hjust=0.5),
        #legend.position = "none", #uncomment to remove colorbar
        plot.background = element_rect(fill = "transparent",colour = NA),
        panel.background = element_rect(fill = "transparent",colour = NA))
)
```

```{r, combine-test-1}
messi + wague + busquets + plot_layout(guides = "collect")
```

```{r, messi-test-2}
barca_sonar %>% 
  filter(str_detect(player.name, "Messi")) %>% 
  ggplot(aes(x=angle.round, y=pct.angle, fill=distance)) + 
  geom_smooth(method = "gam", formula = y ~ poly(x, 5)) +
  coord_polar(start = pi, direction = 1)

messi_sonar <- barca_sonar %>% 
  filter(str_detect(player.name, "Messi"))

messi_sonar %>% 
  ggplot(aes(angle.round, distance)) + 
  geom_col(width = 3) +
  coord_polar(start = pi, direction = 1)

messi_sum <- barca_sum %>% 
  filter(str_detect(player.name, "Messi"))

messi_sum %>% 
  ggplot(aes(pass_angle, pass.length)) + 
  geom_hline(yintercept = seq(0, 60, 10), color = "gray") +
  geom_point(alpha = 0.4) +
  geom_segment( aes(x=pass_angle, xend=pass_angle, y=0, yend=pass.length), alpha = 0.05) +
  coord_polar(start = pi, direction = 1) +
  lims(y = c(-20, 60)) +
  theme_void() +
  annotate(x = 0, y = -20, geom = "text", label = "Messi", size = 8)
```

```{r plotting functions-v1, include = F}

passing_plots <- function(player_name){
  df1 <- barca_sonar %>% 
    filter(str_detect(player.name, player_name))
  
  sonar_plot <- df1 %>% 
    ggplot() +
    geom_hline(yintercept = seq(0, 30, 5), color = "gray") +
    annotate(geom = "text", x = 0, y = seq(0, 30, 5), label = seq(0, 30, 5), color = "gray") + 
    geom_bar(aes(x=angle.round, y=pct.angle, fill=distance), stat="identity") +
    scale_y_continuous(limits=c(-10, 30)) +
    scale_x_continuous(breaks=seq(-180,180, by=90), limits=c(-180,180)) +
    coord_polar(start=pi, direction=1) +
    scale_fill_gradient("Distance (yards)", 
                        high = "#DB0030",
                        low = "#FFED02") +
    labs(x='', y='')+
    theme_void() +
    theme(plot.title = element_text(hjust=0.5),
          legend.position = "none", #uncomment to remove colorbar
          plot.background = element_rect(fill = "transparent",colour = NA),
          panel.background = element_rect(fill = "transparent",colour = NA)) +
    annotate(x = 0, y = -10, geom = "text", label = player_name, size = 8, color = "#004D98")

  
  df2 <- barca_sum %>% 
    filter(str_detect(player.name, player_name))
  
  point_plot <- df2 %>% 
    ggplot(aes(pass_angle, pass_length)) + 
    geom_hline(yintercept = seq(0, 30, 5), color = "gray") +
    annotate(geom = "text", x = 0, y = seq(0, 30, 5), label = seq(0, 30, 5), color = "gray") + 
    geom_point(alpha = 0.8, fill = "#004D98", shape = 21, color = "white") +
    geom_segment( aes(x=pass_angle, xend=pass_angle, y=0, yend=pass_length), alpha = 0.05, color = "#004D98") +
    coord_polar(start = pi, direction = 1) +
    lims(y = c(-10, 30)) +
    theme_void() +
    annotate(x = 0, y = -10, geom = "text", label = player_name, size = 8, color = "#004D98")
  
  list(sonar_plot = sonar_plot, point_plot = point_plot)
  
  sonar_plot + point_plot
}

passing_plots("Fati")


```

```{r plotting functions-v2, include = F}

passing_plots_v2 <- function(player_name){
  df1 <- barca_sonar %>% 
    filter(str_detect(player.name, player_name))
  
  sonar_plot <- df1 %>% 
    ggplot() +
    geom_hline(yintercept = seq(0, 30, 5), color = "gray") +
    annotate(geom = "text", x = 0, y = seq(0, 30, 5), label = seq(0, 30, 5), color = "gray") + 
    geom_bar(aes(x=angle.round, y=pct.angle, fill=distance), stat="identity") +
#    scale_y_continuous(limits=c(-10, 30)) +
    scale_x_continuous(breaks=seq(-180,180, by=90), limits=c(-180,180)) +
    coord_polar(start=pi, direction=1) +
    scale_fill_gradient("Distance (yards)", 
                        high = "#DB0030",
                        low = "#FFED02") +
    labs(x='', y='')+
    theme_void() +
    theme(plot.title = element_text(hjust=0.5),
          legend.position = "none", #uncomment to remove colorbar
          plot.background = element_rect(fill = "transparent",colour = NA),
          panel.background = element_rect(fill = "transparent",colour = NA))

  
  df2 <- barca_sum %>% 
    filter(str_detect(player.name, player_name))
  
  point_plot <- df2 %>% 
    ggplot(aes(pass_angle, pass_length)) + 
    geom_hline(yintercept = seq(0, 30, 5), color = "gray") +
    annotate(geom = "text", x = 0, y = seq(0, 30, 5), label = seq(0, 30, 5), color = "gray") + 
    geom_point(alpha = 0.8, fill = "#004D98", shape = 21, color = "white") +
    geom_segment( aes(x=pass_angle, xend=pass_angle, y=0, yend=pass_length), alpha = 0.05, color = "#004D98") +
    coord_polar(start = pi, direction = 1) +
#    lims(y = c(-10, 30)) +
    theme_void()
  
  list(sonar_plot = sonar_plot, point_plot = point_plot)
  
  sonar_plot + point_plot + 
    plot_annotation(title = player_name,
                    subtitle = "Barcelona, 2019-2020",
                    caption = "Data provide by StatsBomb")
}

passing_plots_v2("Frenkie de Jong")

passing_plots_v2("Umtiti")


```