---
title: "Soccer Data #3"
author: "CS"
date: "10/20/2021"
output: html_document
---

These are all of the shots from [Arsenal's Invincibles Season in 2003-2004](https://en.wikipedia.org/wiki/2003%E2%80%9304_Arsenal_F.C._season). The second plot shows the shots and their corresponding xG.

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  fig.retina = 3,
  fig.path = here::here("exports", "soccer", "Plots", "/"),
  out.width = "100%"
)
pacman::p_load(pacman, tidyverse, janitor, here, rio, job, skimr, patchwork, viridis, paletteer, crsp)


theme_set(theme_bw(base_size = 15) + theme(legend.position = "bottom", legend.direction = "horizontal"))
```

```{r data, include = F}
p_load(StatsBombR, SBpitch, soccermatics, sportyR)

comps <- FreeCompetitions()

afc <- comps %>% 
  filter(competition_id == 2, season_id == 44) %>% 
  FreeMatches()

afc_raw <-  StatsBombFreeEvents(MatchesDF = afc) %>% 
  allclean() %>% 
  clean_names()

afc_shot <- afc_raw %>% 
  select(player_name, matches("shot")) %>% 
  filter(!is.na(shot_statsbomb_xg)) %>% 
  filter(shot_outcome_name != "Off T")


```

```{r shot-location-plot, include = FALSE}
geom_soccer(league = "Premier") + 
  ggplot(aes(shot_end_location_x, shot_end_location_y, color = shot_statsbomb_xg), data = afc_shot) + 
  geom_point(data = afc_shot)
```

```{r shot-location-plot-2, include = TRUE}
geom_soccer(league = "premier", touchline_length = 120, goal_line_length = 80) +
  geom_point(data = afc_shot, aes(shot_end_location_x-61, shot_end_location_y-40), 
             shape = 21, fill = "white", color = "black")
```

```{r shot-location-plot-3, include = TRUE}
geom_soccer(league = "premier", 
            touchline_length = 120, goal_line_length = 80, 
            full_surf = F, rotate = T, grass_color = "black") +
  geom_point(data = afc_shot, 
             aes(y = -shot_end_location_x+60, x = shot_end_location_y-40, 
                 color = shot_statsbomb_xg), alpha = 0.4, size = 2) + 
  scale_color_paletteer_c("ggthemes::Temperature Diverging", 
                          guide = guide_colorbar(title = "xG", title.position = "top", 
                                                 title.hjust = 0.5, 
                                                 barwidth = 20, barheight = 0.5,)) +
  theme(legend.position = c(0.5, 0.7), legend.direction = "horizontal", 
        legend.text = element_text(color = "white"), legend.background = element_rect(fill = "black"),
        legend.title = element_text(color = "white"))


```